name: Publish to PyPI

on:
  push:
    tags:
      - "v*" # Trigger on any tag that starts with 'v'

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install build dependencies
        run: |
          pip install hatchling

      - name: Build package
        run: |
          python -m hatchling build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          # Uncomment the following line if you want to publish to TestPyPI first
          # repository-url: https://test.pypi.org/legacy/
          verbose: true
